# Generated by Django 6.0.1 on 2026-04-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_course_module_lesson_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='module',
        ),
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
