# Generated by Django 6.0.4 on 2026-04-13 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_description_en_course_description_fr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('title_my', models.CharField(max_length=200, null=True)),
                ('title_hi', models.CharField(max_length=200, null=True)),
                ('step_type', models.CharField(choices=[('theory', 'Theory'), ('practice', 'Practice'), ('quiz', 'Quiz')], default='theory', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Theory or instruction content (HTML allowed)')),
                ('content_en', models.TextField(blank=True, help_text='Theory or instruction content (HTML allowed)', null=True)),
                ('content_fr', models.TextField(blank=True, help_text='Theory or instruction content (HTML allowed)', null=True)),
                ('content_my', models.TextField(blank=True, help_text='Theory or instruction content (HTML allowed)', null=True)),
                ('content_hi', models.TextField(blank=True, help_text='Theory or instruction content (HTML allowed)', null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PracticeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('instruction_en', models.TextField(null=True)),
                ('instruction_fr', models.TextField(null=True)),
                ('instruction_my', models.TextField(null=True)),
                ('instruction_hi', models.TextField(null=True)),
                ('starter_content', models.TextField(blank=True)),
                ('success_message', models.CharField(default='Great work. All checks passed.', max_length=255)),
                ('success_message_en', models.CharField(default='Great work. All checks passed.', max_length=255, null=True)),
                ('success_message_fr', models.CharField(default='Great work. All checks passed.', max_length=255, null=True)),
                ('success_message_my', models.CharField(default='Great work. All checks passed.', max_length=255, null=True)),
                ('success_message_hi', models.CharField(default='Great work. All checks passed.', max_length=255, null=True)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_task', to='courses.step')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_content', models.TextField()),
                ('is_passed', models.BooleanField(default=False)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_submissions', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.step')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('title_my', models.CharField(max_length=200, null=True)),
                ('title_hi', models.CharField(max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='step',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='courses.topic'),
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-friendly test label', max_length=120)),
                ('name_en', models.CharField(help_text='Human-friendly test label', max_length=120, null=True)),
                ('name_fr', models.CharField(help_text='Human-friendly test label', max_length=120, null=True)),
                ('name_my', models.CharField(help_text='Human-friendly test label', max_length=120, null=True)),
                ('name_hi', models.CharField(help_text='Human-friendly test label', max_length=120, null=True)),
                ('rule_type', models.CharField(choices=[('contains_text', 'Contains Text'), ('bold_text', 'Bold Text')], default='contains_text', max_length=30)),
                ('expected_value', models.CharField(max_length=500)),
                ('expected_value_en', models.CharField(max_length=500, null=True)),
                ('expected_value_fr', models.CharField(max_length=500, null=True)),
                ('expected_value_my', models.CharField(max_length=500, null=True)),
                ('expected_value_hi', models.CharField(max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('practice_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='courses.practicetask')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('passed', 'Passed')], default='locked', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'step')},
            },
        ),
    ]
