# Generated by Django 6.0.4 on 2026-04-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_step_practicetask_practicesubmission_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='quiz_correct_answer',
            field=models.CharField(blank=True, choices=[('0', 'Option 1'), ('1', 'Option 2')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='step',
            name='quiz_option_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='step',
            name='quiz_option_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='step',
            name='quiz_question',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('practice', 'Practice'), ('quiz', 'Quiz'), ('workshop', 'Workshop')], default='theory', max_length=20),
        ),
    ]
