# Generated by Django 6.0.4 on 2026-04-18 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_step_quiz_correct_answer_step_quiz_option_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='workshop_min_words',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='step',
            name='workshop_required_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='WorkshopSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='workshop_submissions/')),
                ('is_passed', models.BooleanField(default=False)),
                ('feedback', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_submissions', to='courses.step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
