# Generated by Django 6.0.1 on 2026-07-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_step_workshop_min_words_step_workshop_required_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='quiz_option_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='step',
            name='quiz_option_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='step',
            name='quiz_correct_answer',
            field=models.CharField(blank=True, choices=[('0', 'Option 1'), ('1', 'Option 2'), ('2', 'Option 3'), ('3', 'Option 4')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('quiz', 'Quiz'), ('workshop', 'Workshop')], default='theory', max_length=20),
        ),
    ]
